In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline
warnings.filterwarnings('ignore')

In [31]:
dp = pd.read_csv('data/std.csv')
dp.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [32]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [33]:
# checks missing values
dp.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [34]:
# checks duplicates
dp.duplicated().sum()

0

In [35]:
# no of unique values in each column
dp.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [36]:
dp.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [37]:
dp.shape

(1000, 8)

In [38]:
numerical_features = [col for col in dp.columns if dp[col].dtype != 'O']
categorical_features = [col for col in dp.columns if dp[col].dtype == 'O']

print("We have {} numerical features: {}".format(len(numerical_features),numerical_features))
print("We have {} categorical features: {}".format(len(categorical_features),categorical_features))

We have 3 numerical features: ['math score', 'reading score', 'writing score']
We have 5 categorical features: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

In [39]:
for i in categorical_features:
    print(dp[i].value_counts(),"\n")

gender
female    518
male      482
Name: count, dtype: int64

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

test preparation course
none         642
completed    358
Name: count, dtype: int64

In [40]:
dp.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [41]:
dp['TotalScore'] = dp['math score'] + dp['reading score'] + dp['writing score']
dp['Average'] = dp['TotalScore'] / 3
dp.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,TotalScore,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333

In [55]:
dp.rename(columns={
    'gender': 'gender',
    'race/ethnicity': 'race_ethnicity',
    'parental_level_of_education': 'parental_level_of_education',
    'lunch': 'lunch',
    'test_preparation_course': 'test preparation course',
    'math_score': 'math score',
    'reading_score': 'reading score',
    'writing_score': 'writing score'
}, inplace=True)

In [57]:
dp.head()

,gender,race_ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,TotalScore,Average,race_ethnicity
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,group B
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,group C
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,group B
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,group A
4,male,group C,some college,standard,none,76,78,75,229,76.333333,group C

In [44]:
# gender	race_ethnicity	parental_level_of_education	lunch	test_preparation_course	math_score	reading_score	writing_score

In [51]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   TotalScore                   1000 non-null   int64
 9   Average                      1000 non-null   float64
 10  race_ethnicity               1000 non-null   object
dtypes: float64(1), int64(4), object(6)
memory usage: 86.1+ KB